// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAza8yxoOtNhFbgb9qHDijoBlOing5eQjs',
    appId: '1:202588344394:web:2dc1215c0a4b2c5aad96b3',
    messagingSenderId: '202588344394',
    projectId: 'fa-trial-3d01c',
    authDomain: 'fa-trial-3d01c.firebaseapp.com',
    storageBucket: 'fa-trial-3d01c.firebasestorage.app',
    measurementId: 'G-SX5H3BCSZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU5L6kCjhxjL33UMDm4aoJDEIh4LiD4mA',
    appId: '1:202588344394:android:abbd9c2b7f6ae753ad96b3',
    messagingSenderId: '202588344394',
    projectId: 'fa-trial-3d01c',
    storageBucket: 'fa-trial-3d01c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN0tBqOVW4cMTJM0p7KAwz1BTFtITFMkg',
    appId: '1:202588344394:ios:dc8d8405423871f7ad96b3',
    messagingSenderId: '202588344394',
    projectId: 'fa-trial-3d01c',
    storageBucket: 'fa-trial-3d01c.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN0tBqOVW4cMTJM0p7KAwz1BTFtITFMkg',
    appId: '1:202588344394:ios:dc8d8405423871f7ad96b3',
    messagingSenderId: '202588344394',
    projectId: 'fa-trial-3d01c',
    storageBucket: 'fa-trial-3d01c.firebasestorage.app',
    iosBundleId: 'com.example.trial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAza8yxoOtNhFbgb9qHDijoBlOing5eQjs',
    appId: '1:202588344394:web:d3c5a69664256f30ad96b3',
    messagingSenderId: '202588344394',
    projectId: 'fa-trial-3d01c',
    authDomain: 'fa-trial-3d01c.firebaseapp.com',
    storageBucket: 'fa-trial-3d01c.firebasestorage.app',
    measurementId: 'G-06RPZ8X6B9',
  );
}
